#!/usr/bin/env bash

set -e  # Arrête le script dès une erreur


# Fonction pour traiter l'entrée et gérer le préfixe
input_chat() {
  receiver=""
  while [[ -z "$receiver" ]]; do
      echo -n "Qui est votre destinataire ? : " >&2
      read -r receiver
  done
  while true; do
      # Lire une ligne de l'entrée standard
      if read -r line; then
          # Ajouter le préfixe au message et l'envoyer
          echo "$receiver $line"
      else
          # Si Ctrl+D est détecté (fin d'entrée), demander un nouveau préfixe
          echo -n "Changement de destinataire. Entrez un nouveau pseudo : " >&2
          read -r receiver
          if [[ -z "$receiver" ]]; then
              exit 3
          fi
          # receiver=${receiver:-bob}  # Si aucune entrée, remettre "bob" par défaut
      fi
  done
  }

# Fonction principale
main() {
    if [ "$#" -ge 1 ]; then
        # Connecter la sortie de process_input à ./chat
        input_chat | ./chat "$@"
    else
        echo "Erreur : Veuillez fournir au moins un argument." >&2
        exit 1
    fi
}

main "$@"
