

#ifndef PROJETOS_CODESERREURS_HPP
#define PROJETOS_CODESERREURS_HPP
enum {
    CODE_RETOUR_NORMAL,
    CODE_RETOUR_PARAMETRES_MANQUANTS,
    CODE_RETOUR_PSEUDO_TROP_LONG,
    CODE_RETOUR_PSEUDO_CARACTERES_INVALIDES,
    CODE_RETOUR_ARRET_SIGINT,
    CODE_RETOUR_ERREUR_AUTRE
};


#endif //PROJETOS_CODESERREURS_HPP
